### ISSUE TITLE
Content updates (errors on test)

### ISSUE THREAD

**Issue by dgallardo** [ucb-las/las-project#351]
Examples of things to test:
- Check for missing or erroneous information
- Titles we may need to change for clarity or shorten
- Typos

**Comment by dgallardo** [comment]
page missing..
[] asdfkj

**Comment by kcleonardo** [comment]
- [ ] ~~missing links on http://test-lhrdredesign.pantheon.berkeley.edu/lbs/overview-of-procedures-for-funding-approval-requests~~
- [x] for topic results, I suggest showing snippets instead of full content and possibly exclude the list of topics under each result
- [x] screenshot of Connexxus missing in http://test-lhrdredesign.pantheon.berkeley.edu/lbs/how-to-book-a-flight-for-yourself-through-connexxus
- [x] ~~remove Richard Tran's name, e.g., http://test-lhrdredesign.pantheon.berkeley.edu/lbs/how-to-book-a-flight-for-yourself-through-connexxus~~
- [x] some contents missing, e.g., travel insurance
- [x] where will the "what's new" section (see top of this page: http://www.lib.berkeley.edu/Staff/LBS/travel.html) be in the new site?
- [x] add contacts for other LAS units on this page: http://test-lhrdredesign.pantheon.berkeley.edu/contact, e.g., contract and grants: libaward@lists.berkeley.edu.

**Comment by dgallardo** [comment]
- [x] update links to internal las_resources in content, url for a href should be /sites/default/files/las_resources/[filename]

**Comment by kcleonardo** [comment]
- [x] Richard Tran's name should be removed from this page: http://test-lhrdredesign.pantheon.berkeley.edu/about-us
